#!/usr/bin/env python3
"""Produce a licence inventory of everything installed, for a security review.

A bank's compliance team will ask what this software and its dependencies are
licensed under. That question cannot be answered honestly from a list written
by hand months earlier: pins move, transitive dependencies appear, and the
answer that matters is about the environment actually deployed. So this reads
the installed distributions on THIS machine and reports what is really there.

    python scripts/license_inventory.py                  # to stdout
    python scripts/license_inventory.py -o licences.md   # to a file
    python scripts/license_inventory.py --strict          # exit 1 on copyleft

Model weights are NOT pip packages and are not covered here; their licences
are in docs/LICENSES.md, and they are the ones that usually need a decision.
"""

from __future__ import annotations

import argparse
import sys
from importlib.metadata import distributions

# Licences a bank's review will stop on. Flagged, not judged: whether a
# licence is acceptable depends on how the software is distributed, which is a
# question for the bank's legal team and not for this script.
FLAGGED = ("GPL", "AGPL", "LGPL", "MPL", "EPL", "CDDL", "SSPL", "BUSL",
           "Commons Clause", "NonCommercial", "NC-", "Proprietary")

# Permissive licences carry no obligation worth flagging, but an UNKNOWN one
# does: it means nobody has looked.
UNKNOWN = "UNKNOWN"


def _licence_of(dist) -> str:  # noqa: ANN001
    meta = dist.metadata
    # PEP 639 first: modern wheels carry a clean SPDX expression.
    value = meta.get("License-Expression")
    if value:
        return value.strip()
    classifiers = [c for c in meta.get_all("Classifier") or [] if c.startswith("License ::")]
    if classifiers:
        return " / ".join(c.split("::")[-1].strip() for c in classifiers)
    value = (meta.get("License") or "").strip()
    if value and len(value) <= 80 and "\n" not in value:
        return value
    # Some projects paste the whole licence text into the License field.
    return f"{value.splitlines()[0][:60]}..." if value else UNKNOWN


def inventory() -> list[tuple[str, str, str]]:
    rows = []
    for dist in distributions():
        name = dist.metadata.get("Name")
        if not name:
            continue                                  # pragma: no cover - broken dist
        rows.append((name, dist.version or "?", _licence_of(dist)))
    # Deduplicate: a dist can appear twice when several site-dirs are active.
    return sorted({r[0].lower(): r for r in rows}.values(), key=lambda r: r[0].lower())


def flagged(rows: list[tuple[str, str, str]]) -> list[tuple[str, str, str]]:
    return [r for r in rows
            if r[2] == UNKNOWN or any(f.lower() in r[2].lower() for f in FLAGGED)]


def render(rows: list[tuple[str, str, str]]) -> str:
    out = [
        "# Third-party licences",
        "",
        "Generated by `scripts/license_inventory.py` from the packages installed in",
        "the environment it was run in. Regenerate it on the deployed machine - that",
        "is the environment the answer is about.",
        "",
        f"{len(rows)} distributions.",
        "",
        "| Package | Version | Licence |",
        "|---|---|---|",
    ]
    out += [f"| {n} | {v} | {lic} |" for n, v, lic in rows]
    needs_review = flagged(rows)
    out += ["", "## Needs a look", ""]
    if needs_review:
        out += ["These are copyleft, restricted, or carry no declared licence. Flagged",
                "for a human to decide, not judged here.", ""]
        out += [f"- **{n}** {v} — {lic}" for n, v, lic in needs_review]
    else:
        out += ["Nothing copyleft, restricted, or undeclared among the installed",
                "packages."]
    out += ["",
            "## Not covered here",
            "",
            "Model weights are not pip packages. Their licences - including the one",
            "gated model and any judge model chosen at deployment time - are in",
            "docs/LICENSES.md, and they are the ones that usually need a decision.",
            ""]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-o", "--output", default=None, help="write here instead of stdout")
    parser.add_argument("--strict", action="store_true",
                        help="exit 1 if anything is copyleft, restricted or undeclared")
    args = parser.parse_args()

    rows = inventory()
    text = render(rows)
    if args.output:
        from pathlib import Path

        Path(args.output).write_text(text, encoding="utf-8")
        print(f"wrote {args.output} — {len(rows)} distributions")
    else:
        print(text)

    needs_review = flagged(rows)
    if needs_review:
        print(f"\n{len(needs_review)} package(s) need a look:", file=sys.stderr)
        for name, version, lic in needs_review:
            print(f"  {name} {version}: {lic}", file=sys.stderr)
        if args.strict:
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
